services:
  - type: web
    name: freshcut-back
    env: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/backend-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        value: "mongodb+srv://freshcut0410_db_user:Pasto1307@cluster0.x2tpt1t.mongodb.net/freshcut?retryWrites=true&w=majority&appName=Cluster0"
